version: "3.7"
services:
  backend:
    build: ./wordament
    environment:
      PORT: 8000
    ports:
      - 8000:8000

  frontend:
    image: nginx:1.19.8-alpine
    ports:
      - target: 80
        published: 8080
        protocol: tcp
        mode: host    
    volumes:
      - ./html_client/nginx.conf:/etc/nginx/conf.d/default.conf
      - ./html_client/index.html:/usr/share/nginx/html/index.html

  # client:
  #   build: ./simple_client
  #   environment:
  #     SERVER_URL: "http://0.0.0.0:8000/api"
  #   depends_on:
  #     - "backend"

