version: "3.7"
services:
  wordament:
    build: ./wordament
    environment:
      PORT: 8000
    ports:
      - 8000:8000

  # client:
  #   build: ./simple_client
  #   environment:
  #     SERVER_URL: "http://0.0.0.0:8000/api"
  #   depends_on:
  #     - "wordament"

