apiVersion: v1
kind: Pod
metadata:
  name: wordament
  namespace: wordament
spec:
  containers:
  - name: wordament
    image: test_wordament:latest
    imagePullPolicy: Never
    ports:
      - name: debug
        containerPort: 5678          
      - name: http
        containerPort: 8000

    env:
      - name: PORT
        value: "8000"
      - name: DEBUGGER
        value: "True"
      - name: WAIT
        value: "False"