apiVersion: skaffold/v1beta11
kind: Config

profiles:
  - name: testlocaldockerk8s

    build:
      artifacts:
      - image: test_wordament
        context: ./

      tagPolicy:
        sha256: {}

    deploy:
      kubectl:
        manifests:
          - ../k8s/wordament*

